### ISSUE TITLE
Changing websocket url

### ISSUE THREAD

**Issue by DenizTC** [nathantsoi/vue-native-websocket#10]
How do I change the websocket url string? The component needs to connect to a different websocket url depending on the current url.

Here is an example of my component:
```
<script>
import VueNativeSock from 'vue-native-websocket'
Vue.use(VueNativeSock, 'ws://myserver:8080/logs?id=' + this.$route.params.id);

export default {
...
}
</script>
```

So if the current url is http://example/results/1234, then I need to open the connection to ws://myserver:8080/logs?id=1234.

**Comment by sirb0rab0g1** [comment]
did you fix this already ? i got the same pattern in url

**Comment by DenizTC** [comment]
@sirb0rab0g1 I was never able to figure it out with this library. I ended up switching to https://developer.mozilla.org/en-US/docs/Web/API/WebSocket, which solved my issue.

**Comment by nathantsoi** [comment]
Interesting use case here. I would expect one would usually use a single websocket endpoint and let the traffic be routed depending on message type. Unfortunately its not currently possible to change websocket instances per path. I'll close this for now, but feel free to open a PR if anyone implements this or continue discussion on this thread.

**Comment by kdenny** [comment]
@DenizTC Do you happen to have any examples showing the Mozilla library used in Vue?

**Comment by quangIO** [comment]
@kdenny It is not Mozilla library. All modern browsers support WebSocket natively and you can just write normal javascript. [WebSocket example](https://gist.github.com/quangIO/82e1617dcbf9cf9a9f6a8892df8c475b)

**Comment by aleksandrmelnyk** [comment]
Most of websocket backend implementations have routers, based on url path, so this feature would be pretty useful. It should be possible to connect/send messages to /particular/endpoint.

**Comment by GopherJ** [comment]
I got the same problem....I would like to make user being able to switch between local and cloud server.

**Comment by pathnirvana** [comment]
I have the same use case and dumping this library in favor of the native browser WebSocket @quangIO Thanks for the example.
