### ISSUE TITLE
Use namespace also for actions

### ISSUE THREAD

**Issue by ThomasKlessen** [nathantsoi/vue-native-websocket#23]
I do not know wether this is desired behavior, but i use namespaced stores und vue-native-websocket is not able to call actions accordingly. 

It is because you do not include the namespace when generating the action:
`if (msg.mutation) {
        target = [msg.namespace || '', msg.mutation].filter((e) => !!e).join('/')
      } else if (msg.action) {
        method = 'dispatch'
        target = msg.action
      }`

In my opinion this is a bug and i could create a pull-request if you want to?

**Comment by nathantsoi** [comment]
ahh good catch, a PR would be great, Thomas! could you check the tests as
well and add one if this isnt covered?

**Comment by ThomasKlessen** [comment]
I added the PR already.
But you are right. A test is still missing.
Give me some time tomorrow ;)

Thx for responding!

**Comment by ThomasKlessen** [comment]
Everything is done.
Btw: Nice code imho.
;)

**Comment by ThomasKlessen** [comment]
Hi Nathan,
Is there anything else i could do to help you merging?

**Comment by ThomasKlessen** [comment]
Thx for merging.
