### ISSUE TITLE
'ws' is not defined

### ISSUE THREAD

**Issue by flip111** [nathantsoi/vue-native-websocket#29]
In the usage i get an eslint error on `ws.WS_RECONNECT` and `ws.WS_RECONNECT_ERROR` perhaps the [global WebSocket object](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) can be used here instead?

**Comment by weglov** [comment]
It was a typo in README use: `SOCKET_RECONNECT` and `SOCKET_RECONNECT_ERROR`

**Comment by Vankerkom** [comment]
@weglov Mind updating the readme with this? I was confused at first myself when I tried to set-up the example.
