### ISSUE TITLE
After reconnected websocket, this.$socket.send , can not send message, 

### ISSUE THREAD

**Issue by qq476649388** [nathantsoi/vue-native-websocket#36]
After reconnected websocket, this.$socket.send , can not send message, chrome console Error message :"WebSocket is already in CLOSING or CLOSED state" 。in other words , the "socket Instance" in vuex's state is not updated.  still the previous one.

**Comment by dslokva** [comment]
also have the same issue.

**Comment by wr200m** [comment]
I have the same issue - The socket instance of Vue.prototype.$socket is not updated to point to the new WebSocket created after reconnection.

**Comment by markz440** [comment]
I have the same issue. Was anybody able to solve this?

**Comment by StanleyGulevich** [comment]
I have the same issue too. I try to input prototype $socket in reconnect func but it have no result. Pls help us cause this is very important issue

**Comment by felix9ia** [comment]
```
   SOCKET_ONOPEN (state, event) {
      Vue.prototype.$socket = event.currentTarget
      state.socket.isConnected = true
    }
```

I use VueX，is right? I solved the problem.

**Comment by dwsVad** [comment]
Replace :
`
Vue.prototype.$socket = observer.WebSocket
`
To: 
`
Emitter.addListener('onopen', (event) => {
                console.log("SOCKET MAIN", event);
                Vue.prototype.$socket = event.currentTarget
            });
`

**Comment by ArtStepanyuk** [comment]
For now, following @felix9ia approach but it should be fixed on library level

**Comment by weglov** [comment]
pr with the fix: https://github.com/nathantsoi/vue-native-websocket/pull/65 
please review, I find only this solution with the current structure

**Comment by weglov** [comment]
resolve in 2.0.9
