### ISSUE TITLE
How to disconnect properly?

### ISSUE THREAD

**Issue by wr200m** [nathantsoi/vue-native-websocket#41]
Can someone please point me to the proper way to disconnect - I suppose $socket.close() should be used. But if reconnect is enabled - how to disable it. Thank you.

**Comment by wr200m** [comment]
Here's my own solution - inside Main.js I use $connect and $disconnect to require an explicit request to connect, i.e. a new observer instance is constructed each time when $connect, and the $socket is closed when $disconnect. This way I can control the reconnection flag when I actually want to disconnect the web socket.

    let observer = null

    Vue.prototype.$connect = function () {
      observer = new Observer(connection, opts)
      Vue.prototype.$socket = observer.WebSocket
    }   
    Vue.prototype.$disconnect = function () {
      observer.reconnection = false
      Vue.prototype.$socket.close()
      delete Vue.prototype.$socket
    }

**Comment by alex-dow** [comment]
Hi @wr200m , where did you make these changes? I have a similar need where I want to manually connect to the websocket rather than have it be automatic.

**Comment by alex-dow** [comment]
never mind, I have since figured it out.

`import Observer from './Observer'
import Emitter from './Emitter'

export default {

  install (Vue, connection, opts = {}) {
    if (!connection) { throw new Error('[vue-native-socket] cannot locate connection') }

    let observer = null;

    Vue.prototype.$connect = function() {
        observer = new Observer(connection, opts);
        Vue.prototype.$socket = observer.WebSocket;
    };  

    Vue.prototype.$disconnect = function() {
        observer.reconnection = false;
        Vue.prototype.$socket.close();
        delete Vue.prototype.$socket;
    };`

**Comment by NaughtyMC** [comment]
@alex-dow @wr200m 
Looks like I have the same use case - we can't be the only ones. Unless one of you wants to take the lead on the PR, I will plan on using your code to add a `connectManually` property to the config options.

**Comment by wr200m** [comment]
I made a fork earlier and used that in my project. I was struggling with using the reconnection of this plugin in my use case, even when I didn't need to control the timing of connection. But I did not look further as to whether that had to do with my change or it was something inherent with the plugin as is. I'm traveling these days and won't be making a pull request for a month. If you want to proceed with PR, please go ahead.
