### ISSUE TITLE
After reconnect, socket is in readyState 3

### ISSUE THREAD

**Issue by markz440** [nathantsoi/vue-native-websocket#42]
Hi.

I am having problems using the socket after it is closed and (successfully) reconnected.
Although after the reconnect I get the ONOPEN event, the readyState of the socket is 3, meaning CLOSED or CLOSING.

I am using the sockets with the Vuex store, and I am assigning the Vue.prototype.$socket to store.$socket, to be able to access the socket in the store.

Sample of the code

```
        // socket mutations
        SOCKET_ONOPEN (state, event) {
            state.socket.isConnected = true
            console.log('connected ...', this.$socket)
        },
```
The first time the code is ran the socket is ok, in readyState 1, after reconnect the readyState remains 3

Any ideas?

**Comment by felix9ia** [comment]
How did you fix it?

**Comment by felix9ia** [comment]
```
   SOCKET_ONOPEN (state, event) {
      Vue.prototype.$socket = event.currentTarget
      state.socket.isConnected = true
    }
```
