### ISSUE TITLE
Event listeners without store

### ISSUE THREAD

**Issue by xtrinch** [nathantsoi/vue-native-websocket#5]
How exactly can I listen to events if I do not have a store?

I've tried this in my created method if my main component, but it's not firing:

`	this.$options.sockets.SOCKET_ONMESSAGE = (data) => {console.log("a message")}
`

**Comment by nathantsoi** [comment]
try:

```
this.$options.sockets.onmessage = (data) => {console.log("a message")}
```

see https://github.com/nathantsoi/vue-native-websocket/blob/master/src/Observer.js#L21-L27 for more
