### ISSUE TITLE
Proxy is not defined - IE 11

### ISSUE THREAD

**Issue by dariuszjastrzebski** [nathantsoi/vue-native-websocket#51]
Hello,

In Main.js file you use Proxy object and it's causes that my app not work in IE 11, because in IE 11 there is no Proxy object. 

How can I resolve it? Maybe some Polyfill?

**Comment by mkody** [comment]
Older browsers don't support [ES6's Proxy object](https://kangax.github.io/compat-table/es6/#test-Proxy).
I'm getting a lot of Sentry logs from iOS 9.3.5 or Android 4.4.2/5.1.1 (and for some reason Facebook's internal browser on Android 6.0 too).

There's a polyfill here: https://github.com/GoogleChrome/proxy-polyfill
I'll give it a shot and see if I get any new reports.

**Comment by mikhailian** [comment]
Nope, [proxy-polyfill](ttps://github.com/GoogleChrome/proxy-polyfill) does not work because it does not support `deleteProperty`.

**Comment by TheHugoBoss** [comment]
Any workarounds for this?

**Comment by mikhailian** [comment]
AFAIU, the problem is in the syntax of [Dynamic socket event listeners](https://github.com/nathantsoi/vue-native-websocket#dynamic-socket-event-listeners).  If the authors used a more traditional syntax, that would  be possible. Otherwise, I do not see how.
