### ISSUE TITLE
Cant set headers when connecting?

### ISSUE THREAD

**Issue by serzhiio** [nathantsoi/vue-native-websocket#79]
HI, i noticed that there is no possibility to set headers in connection options.
I hope you will consider adding it...

**Comment by serzhiio** [comment]
Sorry for stupid question. Browser WebSocket library does not supports headers options as Node lib.
Closing :)

**Comment by loong917** [comment]
> Sorry for stupid question. Browser WebSocket library does not supports headers options as Node lib.
> Closing :)

Hello，how to set custom header ?
