### ISSUE TITLE
[Feature Request] Ability to close/open a connection manually when the "reconnection" option is true

### ISSUE THREAD

**Issue by himalr** [nathantsoi/vue-native-websocket#97]
Hello,

I'm currently utilizing the "reconnection" option. however, sometimes, I need to close the connection gracefully from the server side and don't want it to reconnect till I says so.

To me, the most obvious thing to do would be to expose the "Observer" instance from the "observer.WebSocket" instance, but I'm not much of a js dev though. sorry if I missed something obvious.

Thanks.

**Comment by DiDHack** [comment]
Just use connectManually = true. When you want close the connection from the server, send an event from the server which will call vm.$disconnect() on the front-side.

**Comment by himalr** [comment]
But then I have to handle re-connections as well, right? (if the connection drops for some reason)

**Comment by DiDHack** [comment]
As you configure. If reconnection is auto then it will automatically, if is false then you have to handle reconnections by yourself. If you call $disconnect() then reconnection won't fired in anyway (I think you understand it).

**Comment by himalr** [comment]
Yes, I knew that, but I didn't want to handle re-connections myself. that's why I posted this as a feature request.

**Comment by DiDHack** [comment]
> I didn't want to handle re-connections myself
Just use:
connectManually: true,
reconnection: true

So reconnections will be automatically unless you disconnect manually

**Comment by himalr** [comment]
I've tried that and it didn't work. I couldn't find any obvious reason why. 

I mistakenly thought [Main.js#L23](https://github.com/nathantsoi/vue-native-websocket/blob/64c858f61d9f2c9e8434651755b73a2e18fade3b/src/Main.js#L23) explicitly disables re connections, but I just realize it only happen during the `$disconnect()` call.

Maybe I should close this issue and investigate further.
